config/routes.rb
Rails.application.routes.draw do
  
  resources :scholars
  resources :quit_accounts
  get 'coupon/check_coupon'

  resources :member_files
  resources :payments
  
  get 'admin/stats'
  get "/admin/new_payment_for_member/:user_id" => "admin#new_payment_for_member", as: "new_payment_for_member"
  post "/admin/create_payment_for_member" => "admin#create_payment_for_member"

  get "admin/look_up" => "admin#look_up"
  get "admin/edit_user/:user_id" => "admin#edit_user", as: "admin_edit_user"
  
  patch "admin/change_user/:user_id" => "admin#change_user", as: "admin_change_user"

  post "change_payment" => "payments#change_payment", as: "change"
  post "list_searched_members" => "admin#list_searched_members", as: "list_searched_members"

  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", payments: "users/payments", passwords: "users/passwords" }
  get "/profile" => "members#edit"
  get "/dashboard/:member_id" => "members#dashboard", as: "dashboard"
  resources :members 

  resources :addresses
  resources :users

  resources :certificates
  post "certificate/save_certificate" => "certificates#save_certificate"
  
  get "members/:id/add_certificate" => "members#add_certificate"
  post "members/:id/save_certificate" => "members#save_certificate"
  get "members/show_members" => "members#show_members"
  get "member_search" => "addresses#search"
  get "lastnames" => "members#lastnames", as: "lastnames"
  get "search_by_name" => "members#search_by_name", as: "search_by_name"

  get "/contact" => "members#contact", as: "contact"
  post "/send_contact" => "members#send_contact", as: "send_contact"
  
  post "/show_invoice" => "payments#show_invoice", as: "show_invoice"
  post "/show_invoice_sofort" => "payments#show_invoice_sofort", as: "show_invoice_sofort"
  get "/admin/show_invoice/:user_id" =>"admin#show_invoice", as: "admin_show_invoice"
  get "/edit_overview" => "courses#edit_overview", as: "edit_overview"
  
  post "resend_member_email/:user_id" => "admin#resend_member_email"

  get "/admin/:user_id/addresses/new" => "admin#new_address", as: "admin_new_address"
  post "admin/:user_id/addresses" => "admin#create_address", as: "admin_create_address"
  delete "admin/addresses/:id" => "admin#destroy_address", as: "admin_destroy_address"
  get "admin/addresses/:id" => "admin#edit_address", as: "admin_edit_address"
  patch "admin/addresses/:id" => "admin#update_address", as: "admin_update_address"
  get "admin/has_paid" => "admin#has_paid"
  post "admin/send_payment_reminder" => "admin#send_payment_reminder"
  get "admin/new_user" => "admin#new_user"
  post "admin/create_user" => "admin#create_user", as: "admin_create_user"
  post "admin/user/:id" => "admin#delete_user", as: "admin_delete_user"
  get "admin/organizer/new" => "admin#new_organizer"
  get "admin/organizer/edit/:id" => "admin#edit_organizer", as: "admin_edit_organizer"
  post "admin/organizer" => "admin#create_organizer", as: "admin_create_organizer"
  patch "admin/organizer/:id" => "admin#update_organizer", as: "admin_update_organizer"
  get "admin/organizers" => "admin#index_organizers", as: "admin_organizers"
  post "admin/organizers/delete/:id" => "admin#delete_organizer", as: "admin_delete_organizer"
  get "admin/who_became_member" => "admin#who_became_member", as: "who_became_member"
  get "sofort/receive" => "payments#sofort_payment", as: "sofort_payment"

  post "sofort/success" => "payments#sofort_success", as: "sofort_success"
  get "sofort/sent_sofort" => "payments#send_sofort_payment", as: "send_sofort_payment"

  get "coupon/check" => "coupon#check", defaults: { format: "json"}
  get "coupon/used_now" => "coupon#used_now", defaults: { format: "json"} 
  

  get "save_congress_member" => "members#save_congress_member"
  get "admin/quit_member" => "quit_accounts#index", as: "admin_quit_members"

  post "admin/webhooks" => "admin#braintree_webhooks"

  get "scholars/external/:link" => "scholars#external_link"
  post "scholars/list_searched_scholars" => "scholars#list_searched_scholars"

   root 'members#dashboard'

end

app/views/admin/braintree_webhooks.json.erb
{response: "OK"}

app/views/admin/edit_address.html.erb
<h2>Edit address for <%= @member.full_name %></h2>
<%= form_for @address, :url => url_for(:controller => 'admin', :action => 'update_address') do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :office_name %><br>
    <%= f.text_field :office_name %>
  </div>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street, required: true %>
  </div>
  <div class="field">
    <%= f.label :plz %><br>
    <%= f.text_field :plz, required: true %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, required: true %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country, required: true %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :web %><br>
    <%= f.text_field :web %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <% if current_user.member.addresses.count > 0 %>
    <div class="field">
      
      <%= f.label :primary %><br>
      <p>This address will always be shown as your first address in your profile on the FDM- Practitioners list.</p>
      <%= f.check_box :primary %>
    </div>
    <div class="field">
    
      <%= f.label :billing_address %><br>
      <p>Unless this address is also your primary address, we will only use this address to bill you. This address will not appear on the FDM- Practitioners list.</p>
      <%= f.check_box :billing_address %>
    </div>
  <% end %>
 


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/edit_organizer.html.erb
<%= form_for(@organizer, url: admin_update_organizer_path) do |f| %>
  





  <%= f.fields_for :member do |member_fields| %>

    <div class="field">
      <%= member_fields.label :organizer_name %><br />
      <%= member_fields.text_field :organizer_name, class: "form-control" %>
    </div>

    <div class="form-group">
  <strong>Organizer logo</strong><br>

    <% if @organizer.member.avatar.url(:regular) %>
      <%= image_tag @organizer.member.avatar.url(:regular) %>
    <% end %>
    
    <%= member_fields.file_field :avatar %> 
  </div>

  


  <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: "form-control" %>
    </div>



  <div class="col-md-12">
    <br>
    <%= f.submit "Save", class: "btn btn-success", style: "width: 100%;" %>
  </div>
<% end %>

app/views/admin/edit_user.html.erb
<h1>Edit member <%= @member.full_name %></h1>
<p>You can edit all information about this member. Please be aware that any saved changes are final.</p>


<%= form_for @user, url: admin_change_user_path(@member.user.id), :html => {:multipart => true}  do |f| %>
	<div class="from-group">
    <%= f.label :email %><br>
  <%= f.email_field :email, class: "form-control" %>  
  </div>
  

	<%= f.fields_for :member do |member_fields| %>

    <div class="form-group">
      <%= member_fields.label :title %><br />
      <%= member_fields.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= member_fields.label :firstname %><br />
      <%= member_fields.text_field :firstname, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= member_fields.label :lastname %><br />
      <%= member_fields.text_field :lastname, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= member_fields.label :grade %><br />
      <%= member_fields.text_field :grade, class: "form-control" %>
	</div>
  <div class="form-group">
      <%= member_fields.label :job %><br />
      <%= member_fields.text_field :job, class: "form-control" %>
  </div>
    <% if @member.member_type == 0 %>
    <div class="form-group">
      <%= member_fields.label :trial_ends %><br />
      <%= member_fields.date_field :trial_ends, class: "form-control" %>
  </div>
  <% end %>
    <div class="form-group">
      <% unless @member.member_type == 0 %>
      
<%= member_fields.radio_button(:member_type, 1) %>
      <%= member_fields.label(:member_type_1, "Mitglied") %>

      <%= member_fields.radio_button(:member_type, 2) %>
      <%= member_fields.label(:member_type_2, "IC") %>
      <% end %>

      
        
  </div>
      <div class="form-group">
      
      
      <%= member_fields.radio_button(:certified, false) %>
      <%= member_fields.label(:certified_false, "Kein BC") %>

      <%= member_fields.radio_button(:certified, true) %>
      <%= member_fields.label(:certified_true, "BC certified") %>
      
      
        
  </div>

	<div class="form-group">
  <strong>New profile picture</strong><br>

		<% if @member.avatar.url(:regular) %>
			<%= image_tag @member.avatar.url(:regular) %>
		<% end %>
		
		
    
		<%= member_fields.file_field :avatar %> 
	</div>

  <% end %>
  	<br>
	<%= f.submit "Update member" %>

<% end %>

<hr>



<% if @member.user.payments.last  %>
  <% unless @member.user.payments.last.payment_customer_id == nil %>

    <table class="table">
    
    <thead>
      <tr>
        <th>Date of payment</th>
        <th>Next payment</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for payment in @payments %>
        <tr>
          <td><%= payment.created_at.strftime("%Y-%m-%d") %></td>
          <% if payment.status == "settled" %>
            <td><%= (payment.created_at + 1.year).strftime("%Y-%m-%d") %></td>
            <td><%= button_to "Show latest invoice", admin_show_invoice_path(@member.user.id), class: "btn btn-default", method: :get, target: "_blank", params: {id: payment.id} %></td>
          <% else %>
            <td><%= payment.status %></td>
            <td></td>
          <% end %>
          
        </tr>
      <% end %>
    </tbody>
  </table>



  <% else %>
  <%= link_to "new Payment", new_payment_for_member_path(@member.user.id), class: "btn btn-default" %>
  <table class="table">
    
    <thead>
      <tr>
        <th>Date of payment</th>
        <th>Next payment</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for payment in @member.user.payments %>
        <tr>
          <td><%= payment.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= payment.next_payment %></td>
          <% if payment == @member.user.payments.last %>
          <td><%= link_to "Show latest invoice", admin_show_invoice_path(@member.user.id), class: "btn btn-default", target: "_blank"  %></td>
          <% else %>
          <td colspan="" rowspan="" headers=""></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>


  
  <% end %>
  <hr>
<% end %>

<% for address in @member.addresses %>

<div class="address well">
  <div class="table-responsive">
  <table class="table">
    
    <tbody>
      <tr>
        <td width="200">Office name</td>
        <td><%= address.office_name %></td>
      </tr>
      <tr>
        <td width="200">Address</td>
        <td><%= address.street %> <br><%=  address.plz + " " + address.city %> <br> <%= address.country %></td>
      </tr>
      <tr>
        <td>Telephone</td>
        <td><%= address.tel %></td>
      </tr>
      <tr>
        <td>Fax</td>
        <td><%= address.fax %></td>
      </tr>
      <tr>
        <td>Web</td>
        <td><%= address.web %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= address.email %></td>
      </tr>
      <tr>
        <td>Telephone</td>
        <td><%= address.tel %></td>
      </tr>
      
      <tr>
        <td><span title="This is address we show first when people look for you on www.fdm-europe.com">Primary address</span></td>

        <td><strong><%= address.primary  %></strong> <small>(This address will always be shown as your first address in your profile on the FDM- Practitioners list.)</small></td>
      </tr>
      <tr>
        <td><span title="This is address we use for billing the membership fee">Billing address</span></td>
        <td><strong><%= address.billing_address  %></strong> <small>(Unless this address is also your primary address, we will only use this address to bill you. This address will not appear on the FDM- Practitioners list.)</small></td>
      </tr>
      
    </tbody>
  </table>
  <p>
  <%= link_to "Edit address", admin_edit_address_path(address), class: "btn btn-default" %> 
  <% if @member.addresses.count > 1 %>
    <%= link_to 'Delete address', admin_destroy_address_path(address), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
  </p>
    
  </div>
  

</div>


<% end %>
<% if @member.addresses.count < 3 %>
  <p><%= link_to "New address", admin_new_address_path(@member.user), class: "btn btn-success" %></p>
<% end %>

<hr>
<% unless @certificates.empty? %>
<h2>Certificates</h2>

<table class="table">
    
    <thead>
      <tr>
        <th>certificate ID</th>
        <th>date</th>
        <th>city</th>
        <th>type of course</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for certificate in @certificates %>
        <tr>
          <td><%= certificate.special_id %></td>
          <td><%= certificate.course.begin.strftime("%Y.%m.%d") %></td>
          <td><%= certificate.course.city %></td>
          <td><%= certificate.course.course_type %></td>
          <td>
            <%= link_to certificate, class: "button", target: "_blank" do %>
              Show certificate
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <hr>
<% end %>

  <h2>Coupons</h2>

  <table class="table">
    <thead>
      <tr>
        <td>Name</td>
        <td>Code</td>
        <td>Used</td>
        <td>Use date</td>
      </tr>
    </thead>
    <tbody>
      <% for coupon in @coupons %>
        <tr>
          <td><%= coupon.name %></td>
          <td><%= coupon.code %></td>
          <td><%= coupon.code_used %></td>
          <td><%= coupon.updated_at if coupon.code_used == true %></td>
      </tr>
      <% end %>
      
    </tbody>
  </table>

app/views/admin/has_paid.csv.erb
Full name, email, date of last payment, payment type
<% for user in @users %>
<%= user.member.full_name %>, <%= user.email %>, <% if user.payments.last %><%= user.payments.last.created_at %>, <%= user.payments.last.payment_customer_id.nil? ? "Überweisung" : "Card" %>  <% end %>
<% end %>

app/views/admin/index_organizers.html.erb
<h1>Organizer look up</h1>


<table class="table table-striped">
	<tr>
		<th></th>
		<th>name</th>
		<th></th>
		
	</tr>
	
	<% for organizer in User.with_role("organizer") %>
		<tr>
			<td></td>
			<td><%= organizer.member.organizer_name %></td>

			<td> <a href="<%= admin_edit_organizer_path(organizer) %>" class="btn btn-default" title="edit organizer"><i class="fa fa-pencil fa-fw"></i></a> </td> 



			
			
			
		</li>
	<% end %>
</table>

app/views/admin/list_searched_members.js.erb
<% 
html = ""
for member in @members
	html += "<tr>"
	html += "<td>#{h member.user.id}</td>"
	html += "<td>#{h member.full_name}</td>"
	html += "<td>#{h member.addresses.last.city if member.addresses.last}</td>"
	html += "<td>#{h member.member_type > 0 ? "Member" : "Probe"}</td>"
	html += '<td><a href="' + admin_edit_user_path(member) + '" class="btn btn-default" title="edit member"><i class="fa fa-pencil fa-fw"></i></a></td>'
	html += '<td>' + button_to("send login", {action: :resend_member_email, user_id: member.user.id}, class: "btn btn-default", title: "send login information") + '</td>'
	
	html += '<td>' + button_to("delete",{action: :delete_user, id: member.user.id, method: :delete}, data: { confirm: "Are you sure?"}, class: "btn btn-danger", title: "Delete member") + '</td>'
	html += "</tr>"
end

%>



$(".member-list-search tbody").html('<%= raw html %>');

app/views/admin/look_up.html.erb
<h1>Member look up</h1>
<p>Please search by name in order to change all settings.</p>


<%= form_tag :list_searched_members, remote: true do  -%>
	<div class="form-field">
		<%= text_field_tag :person_name, "" ,placeholder: "title firstname lastname grade", class: "form-control" %>
	</div>
	<br>
	<%= submit_tag "Übermitteln", class: "btn mx-auto", style: "width: 100%;" %>

<% end -%>

<h2>Last 10 members</h2>
<table class="table table-striped member-list-search">
	<tr>
		<th></th>
		<th data-sort="string">name</th>
		<th data-sort="string">location</th>
		<th data-sort="string">member email</th>
		<th data-sort="string">member type</th>
		<th></th>
		<th></th>
		<td></td>
	</tr>
	<% @members.each_with_index do |member, i| %>
		<tr>
			<td><%= member.user.id %></td>
			<td><%= member.full_name %></td>
			<td><%= "#{member.addresses.first.city}" unless member.addresses.first.nil? %></td>
			<td><%= member.user.email unless member.user.nil? %></td>
			<td>
				<% if member.member_type == 0 %>
				    Probe
				<% elsif member.member_type == 1 %>
				    Mitglied
				<% else %> 
				   IC
				<% end %> 
			</td>
			<td> <a href="<%= admin_edit_user_path(member) %>" class="btn btn-default" title="edit member"><i class="fa fa-pencil fa-fw"></i></a> </td> 

			<td>
			<% unless member.user.nil? %>
				<%= button_to({action: :resend_member_email, user_id: member.user.id}, class: "btn btn-default", title: "send login information") do %>
					<i class='fa fa-envelope'></i>
				<% end %>
			
			<% end %>
			</td>
			<td><% unless member.user.nil? %>
			<%= button_to({action: :delete_user, id: member.user.id, method: :delete}, data: { confirm: "Are you sure?"}, class: "btn btn-danger", title: "Delete member") do %>
				<i class="fa fa-trash"></i>
				<% end %>
			
			<% end %>
			</td>
		</li>
	<% end %>
</table>

app/views/admin/new_organizer.html.erb
<%= form_for(@organizer, url: admin_create_organizer_path) do |f| %>
  





  <%= f.fields_for :member do |member_fields| %>

    <div class="field">
      <%= member_fields.label :organizer_name %><br />
      <%= member_fields.text_field :organizer_name, class: "form-control" %>
    </div>


  <% end %>



  <div class="col-md-12">
    <br>
    <%= f.submit "Save", class: "btn btn-success", style: "width: 100%;" %>
  </div>
<% end %>

app/views/admin/new_user.html.erb
<%= form_for(@user, url: admin_create_user_path(@user)) do |f| %>
  

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: "form-control", required: true %>
  </div>



  <%= f.fields_for :member do |member_fields| %>

    <div class="field">
      <%= member_fields.label :title %><br />
      <%= member_fields.text_field :title, class: "form-control" %>
    </div>
    <div class="field">
      <%= member_fields.label :firstname %><br />
      <%= member_fields.text_field :firstname, class: "form-control", required: true %>
    </div>
    <div class="field">
      <%= member_fields.label :lastname %><br />
      <%= member_fields.text_field :lastname, class: "form-control", required: true %>
    </div>
    <div class="field">
      <%= member_fields.label :grade %><br />
      <%= member_fields.text_field :grade, class: "form-control" %>


    </div>

  <% end %>



  <div class="col-md-12">
    <br>
    <%= f.submit "Create new member", class: "btn btn-success", style: "width: 100%;" %>
  </div>
<% end %>

app/views/admin/stats.html.erb
<h1>Admin statistics</h1>
<div class="row">
	<div class="col-md-4">
		<div class="well">
			<h3>Member count</h3>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td>full members <%= (Date.today - 1.year).strftime("%Y") %> </td>
							<td><%= Member.where('member_type > 0 AND extract(year  from created_at) = ?', (Date.today - 1.year).strftime("%Y")).count %></td>
						</tr>
						<tr>
							<td>full members <%= (Date.today ).strftime("%Y") %> </td>
							<td><%= NewMember.where('extract(year  from created_at) = ?', (Date.today).strftime("%Y")).count %></td>
						</tr>
						<tr>
							<td>active trial members</td>
							<td><%= Member.where("member_type = 0 AND created_at > ?", Date.today - 120.days).count %></td>
						</tr>
						<tr>
							<td>active regular members</td>
							<td><%= Member.where(member_type: 1).count %></td>
						</tr>
						<tr>
							<td>active IC members</td>
							<td><%= Member.where(member_type: 2).count %></td>
						</tr>

					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-4">

		<div class="well">
			<h3>Course count</h3>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td>Courses in <%= (Date.today - 1.year).strftime("%Y") %></td>
								<td><%= Course.where('extract(year  from begin) = ?', (Date.today - 1.year).strftime("%Y")).count %></td>
							</tr>
							<tr>
								<td>Courses in <%= (Date.today ).strftime("%Y") %></td>
								<td><%= Course.where('extract(year  from begin) = ?', (Date.today).strftime("%Y")).count %></td>
							</tr>
							<tr>
								<td>Courses in <%= (Date.today + 1.year ).strftime("%Y") %></td>
								<td><%= Course.where('extract(year  from begin) = ?', (Date.today +  1.year).strftime("%Y")).count %></td>
							</tr>
						</tbody>
					</table>
				</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well">
			<h3>Organization count</h3>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td>Instructors</td>
							<td><%= User.with_role("instructor").collect.count %></td>
						</tr>
						<tr>
							<td>Organizers</td>
							<td><%= User.with_role("organizer").count %></td>
						</tr>
						<tr>
							<td>Admins</td>
							<td><%= User.with_role("admin").count %></td>
						</tr>
						
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-4">
		<div class="well">
			<h3>Certificate count</h3>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td>Certificate created</td>
							<td><%= Certificate.all.count %></td>
						</tr>
						<tr>
							<td>Certificates claimed</td>
							<td><%= Certificate.where("member_id > 0").count %></td>
						</tr>
						
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well">
			<h3>New Full Members</h3>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td><%= (Date.today - 5.month ).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month - 5.month, Time.now.end_of_month - 5.month).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 4.month ).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month - 4.month, Time.now.end_of_month - 4.month).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 3.month ).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month - 3.month, Time.now.end_of_month - 3.month).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 2.month ).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month - 2.month, Time.now.end_of_month - 2.month).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 1.month ).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month - 1.month, Time.now.end_of_month - 1.month).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today).strftime("%B") %></td>
							<td><%=  NewMember.where("created_at > ? AND created_at < ?", Time.now.beginning_of_month, Time.now.end_of_month).count %></td>
						</tr>
						
					</tbody>
				</table>
			<a href="<%= who_became_member_path %>" class="btn btn-default">New Paying Members</a>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="well">
			<h3>Visits Member Area</h3>
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<td><%= (Date.today - 4.weeks).strftime("%m.%d") %> - <%= (Date.today - 3.weeks).strftime("%m.%d") %></td>
							<td><%= Visit.where("started_at > ? and started_at < ?", Date.today - 4.weeks, Date.today - 3.weeks).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 3.weeks).strftime("%m.%d") %> - <%= (Date.today - 2.weeks).strftime("%m.%d") %></td>
							<td><%= Visit.where("started_at > ? and started_at < ?", Date.today - 3.weeks, Date.today - 2.weeks).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 2.weeks).strftime("%m.%d") %> - <%= (Date.today - 1.weeks).strftime("%m.%d") %></td>
							<td><%= Visit.where("started_at > ? and started_at < ?", Date.today - 2.weeks, Date.today - 1.weeks).count %></td>
						</tr>
						<tr>
							<td><%= (Date.today - 1.weeks).strftime("%m.%d") %> - <%= (Date.today).strftime("%m.%d") %></td>
							<td><%= Visit.where("started_at > ? and started_at < ?", Date.today - 1.weeks, Date.today).count %></td>
						</tr>
						
						
					</tbody>
				</table>
			
			</div>
		</div>
	</div>
	
</div>

app/views/admin/who_became_member.html.erb
<div class="table">
	<table class="table">
		<tr>
			<th>Name</th>
			<th>is certified</th>
			<th>registered on</th>
			<th>Payment</th>
			<th>Date</th>
		</tr>
	<% for new_member in @new_members %>
		<tr>
			<td>
			<%= new_member.user.member.full_name %>			
			</td>
			<td><%= new_member.user.member.certified %></td>
			<td><%= new_member.user.created_at.strftime("%Y-%m-%d") %></td>
			<td><%= new_member.user.payments.last.payment_customer_id.nil? ? "Überweisung" : "Card" if new_member.user.payments.count > 0 %> </td>
			<td><%= new_member.created_at.strftime("%Y-%m-%d") %></td>
		</tr>
	<% end %>
	</table>
</div>