config/routes.rb
Rails.application.routes.draw do
  
  resources :scholars
  resources :quit_accounts
  get 'coupon/check_coupon'

  resources :member_files
  resources :payments
  
  get 'admin/stats'
  get "/admin/new_payment_for_member/:user_id" => "admin#new_payment_for_member", as: "new_payment_for_member"
  post "/admin/create_payment_for_member" => "admin#create_payment_for_member"

  get "admin/look_up" => "admin#look_up"
  get "admin/edit_user/:user_id" => "admin#edit_user", as: "admin_edit_user"
  
  patch "admin/change_user/:user_id" => "admin#change_user", as: "admin_change_user"

  post "change_payment" => "payments#change_payment", as: "change"
  post "list_searched_members" => "admin#list_searched_members", as: "list_searched_members"

  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", payments: "users/payments", passwords: "users/passwords" }
  get "/profile" => "members#edit"
  get "/dashboard/:member_id" => "members#dashboard", as: "dashboard"
  resources :members 

  resources :addresses
  resources :users

  resources :certificates
  post "certificate/save_certificate" => "certificates#save_certificate"
  
  get "members/:id/add_certificate" => "members#add_certificate"
  post "members/:id/save_certificate" => "members#save_certificate"
  get "members/show_members" => "members#show_members"
  get "member_search" => "addresses#search"
  get "lastnames" => "members#lastnames", as: "lastnames"
  get "search_by_name" => "members#search_by_name", as: "search_by_name"

  get "/contact" => "members#contact", as: "contact"
  post "/send_contact" => "members#send_contact", as: "send_contact"
  
  post "/show_invoice" => "payments#show_invoice", as: "show_invoice"
  post "/show_invoice_sofort" => "payments#show_invoice_sofort", as: "show_invoice_sofort"
  get "/admin/show_invoice/:user_id" =>"admin#show_invoice", as: "admin_show_invoice"
  get "/edit_overview" => "courses#edit_overview", as: "edit_overview"
  
  post "resend_member_email/:user_id" => "admin#resend_member_email"

  get "/admin/:user_id/addresses/new" => "admin#new_address", as: "admin_new_address"
  post "admin/:user_id/addresses" => "admin#create_address", as: "admin_create_address"
  delete "admin/addresses/:id" => "admin#destroy_address", as: "admin_destroy_address"
  get "admin/addresses/:id" => "admin#edit_address", as: "admin_edit_address"
  patch "admin/addresses/:id" => "admin#update_address", as: "admin_update_address"
  get "admin/has_paid" => "admin#has_paid"
  post "admin/send_payment_reminder" => "admin#send_payment_reminder"
  get "admin/new_user" => "admin#new_user"
  post "admin/create_user" => "admin#create_user", as: "admin_create_user"
  post "admin/user/:id" => "admin#delete_user", as: "admin_delete_user"
  get "admin/organizer/new" => "admin#new_organizer"
  get "admin/organizer/edit/:id" => "admin#edit_organizer", as: "admin_edit_organizer"
  post "admin/organizer" => "admin#create_organizer", as: "admin_create_organizer"
  patch "admin/organizer/:id" => "admin#update_organizer", as: "admin_update_organizer"
  get "admin/organizers" => "admin#index_organizers", as: "admin_organizers"
  post "admin/organizers/delete/:id" => "admin#delete_organizer", as: "admin_delete_organizer"
  get "admin/who_became_member" => "admin#who_became_member", as: "who_became_member"
  get "sofort/receive" => "payments#sofort_payment", as: "sofort_payment"

  post "sofort/success" => "payments#sofort_success", as: "sofort_success"
  get "sofort/sent_sofort" => "payments#send_sofort_payment", as: "send_sofort_payment"

  get "coupon/check" => "coupon#check", defaults: { format: "json"}
  get "coupon/used_now" => "coupon#used_now", defaults: { format: "json"} 
  

  get "save_congress_member" => "members#save_congress_member"
  get "admin/quit_member" => "quit_accounts#index", as: "admin_quit_members"

  post "admin/webhooks" => "admin#braintree_webhooks"

  get "scholars/external/:link" => "scholars#external_link"
  post "scholars/list_searched_scholars" => "scholars#list_searched_scholars"

   root 'members#dashboard'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :user
	has_one :member, :through => :user

	validate :one_payment_per_year, on: "create"

	def one_payment_per_year
		if Payment.where(user_id: self.user_id, next_payment: self.next_payment).count > 0
			errors.add(:next_payment, "There is already a payment with the same next payment date.")
		end
	end

	
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController



  before_filter :authenticate_user!
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create, :new, :change_payment]

  # GET /payments
  # GET /payments.json
  def index
    @user = current_user
    @payments = @user.payments
    @payment = @payments.last
    if current_user.payments.last.nil?
      redirect_to new_payment_path
    
    else
      unless current_user.payments.last.payment_customer_id.nil?
        @payment_info = Braintree::Customer.find(current_user.payments.last.payment_customer_id)
        @subscription = @payment_info.payment_methods.map(&:subscriptions).flatten.last
        token = @subscription.payment_method_token
        @payment_method = Braintree::PaymentMethod.find(token)
      
        @transactions = Braintree::Transaction.search do |search|
          search.customer_id.is @payment_info.id
        end

        @sub
        
        
      end   
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    render :show, notice: "hello"
  end

  # GET /payments/new
  def new
    payment_customer = Braintree::Customer.create(email: current_user.email)
    
    @token = Braintree::ClientToken.generate(
      customer_id: payment_customer.customer.id
    )

    @payment = Payment.new
  end

  def edit
    @token = Braintree::ClientToken.generate(
      customer_id: current_user.payments.last.payment_customer_id
    )
  end

  def create
    sub = Braintree::Subscription.create(
        payment_method_nonce: params[:payment_method_nonce],
        plan_id: "efdma-membership"
      )
      if sub.success?

      @payment = Payment.new(payment_customer_id: sub.subscription.transactions.first.customer_details.id, next_payment: Date.today + 1.year, user_id: current_user.id)
      

      respond_to do |format|
        if @payment.save
          UserMailer.confirmation_payment(current_user).deliver
          UserMailer.member_paid(current_user, sub.subscription.transactions.first.payment_instrument_type).deliver
          if current_user.member.member_type == 0 
            current_user.member.update(member_type: 1) 
            NewMember.create(user_id: current_user.id)  
          end
          
          format.html { redirect_to edit_member_path(current_user.member), notice: 'Payment was successfully created. Please upload a photo and add an address to your profil.' }
          format.json { render :show, status: :created, location: @payment }
        else
          format.html { render :new }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
      else
        errors = ""
        sub.errors.each do |error|
          errors += error.message
        end
        redirect_to new_payment_path, notice: errors
      end

    
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update

  end



  def change_payment
    @customer = Braintree::Customer.find(current_user.payments.last.payment_customer_id)

    subscription_id = @customer.payment_methods.map(&:subscriptions).flatten.first.id
    result = Braintree::Subscription.update(subscription_id, :payment_method_nonce => params[:payment_method_nonce])
    Rails.logger.debug "NEW BRAINTREE PAYMENT: #{result.inspect}"
    if result.success?
      UserMailer.new_payment_method(current_user.id).deliver_now
      redirect_to payments_path, notice: "payment method updated"
    else 
      render :change_payment
    end
    
  end

  def sofort_payment
    

    user = User.find(current_user.id)

    p = Payment.new(user_id: user.id, next_payment: Date.today + 1.year)
    
    respond_to do |format|
      
        if p.save
          UserMailer.confirmation_payment(user).deliver
          UserMailer.member_paid(user, "sofort-ueberweisung").deliver

          if current_user.member.member_type == 0 
              current_user.member.update(member_type: 1) 
              NewMember.create(user_id: current_user.id)  
          end

          format.html { redirect_to edit_member_path(user.member), notice: 'Payment was successfully created. Please upload a photo and add an address to your profil.' }
        end
      
    end
  end

  def send_sofort_payment
    client = Sofort::Client.new
    @response = client.pay(140, 'EFDMA', { success_url: 'http://member.fdm-europe.com/sofort/receive', abort_url: 'http://member.fdm-europe.com/dashboard', language_code: "de", user_variable: current_user.id, notification_url: "http://member.fdm-europe.com/sofort/receive", reason: 'EFDMA Membership' } )
    redirect_to @response["payment_url"]
  end


  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_invoice
    
    if current_user.member.addresses.where(billing_address: true).first.nil?
      redirect_to edit_member_path(current_user.member), notice: "Please add an address in order to create a payment confirmation. (Please check if you billing address is checked as true)."
    else
      @payment
      @transaction = Braintree::Transaction.find(params[:transaction_id])
      @billing_address = current_user.addresses.where(billing_address: true).first
      

      pdf = Prawn::Document.new page_size: "A4"
      image = Rails.root.join('app','assets','images','Logo-4C.jpg').to_s
      pdf.image image, :width => 250, position: :right
      pdf.pad_top (40) {pdf.text "from\nEFDMA\nLerchenfelder Straße 66-68/1/52\n1080 Vienna\nAustria", align: :left, size: 12 }
          
      text_block  = "to\n" + current_user.member.full_name
      text_block += "\n"
      text_block += @billing_address.street + "\n" + @billing_address.plz + " " + @billing_address.city + "\n" +  @billing_address.country+ "\n"

      pdf.pad_top (40) {pdf.text text_block, align: :left, size: 12 }
      pdf.pad_top (40) {pdf.text "Vienna, #{@transaction.created_at.strftime("%Y-%m-%d")}", align: :right, size: 12 }
      pdf.pad_top (10) {pdf.text "Payment confirmation (ID: #{@transaction.id})", align: :left, size: 12, style: :bold }
      pdf.pad_top (20) {pdf.text "Dear #{current_user.member.title} #{current_user.member.firstname} #{current_user.member.lastname} #{current_user.member.grade},\n this is a confirmation of your payment for the EFDMA membership fee for the next year.", align: :left, size: 12}
      pdf.pad_top (20) {pdf.text "We successfully received your payment of € #{@transaction.amount}.", align: :left, size: 12, style: :bold}
      pdf.pad_top (20) {pdf.text "Thank you for being a part of EFDMA.", align: :left, size: 12}
      pdf.pad_top (40) {pdf.text "Yours sincerely,\n\n Lars Werner\nTreasurer EFDMA", align: :left, size: 12}

      pdf.bounding_box([0,50], width: 150, height: 50) do
        pdf.text "EFDMA\nLerchenfelder Straße 66-68/1/52\nA-1080 Vienna", size: 10
      end
      pdf.bounding_box([190,50], width: 150, height: 50) do
        pdf.text "www.fdm-europe.com\noffice@fdm-europe.com\nZVR 898629488", size: 10, align: :center
      end
      pdf.bounding_box([370,50], width: 150, height: 50) do
        pdf.text "IBAN: AT401200050030001405\nBIC:BKAUATWW\nBank Austria - Creditanstalt", size: 10, align: :right
      end

      send_data pdf.render, filename: "invoice_EFDMA_#{current_user.id}.pdf", type: "application/pdf"
    end
  end 






 def show_invoice_sofort

      @user = current_user
      @payment = Payment.find(params[:id])
    
    if current_user.member.addresses.where(billing_address: true).first.nil?
      redirect_to edit_member_path(current_user.member), notice: "Please add an address in order to create a payment confirmation. (Please check if you billing address is checked as true)."
    else
      
      @billing_address = current_user.addresses.where(billing_address: true).first

      pdf = Prawn::Document.new page_size: "A4"
      image = Rails.root.join('app','assets','images','Logo-4C.jpg').to_s
      pdf.image image, :width => 250, position: :right
      pdf.pad_top (40) {pdf.text "from\nEFDMA\nLerchenfelder Straße 66-68/1/52\n1080 Vienna\nAustria", align: :left, size: 12 }
          
      text_block  = "to\n" + current_user.member.full_name
      text_block += "\n"
      text_block += @billing_address.street + "\n" + @billing_address.plz + " " + @billing_address.city + "\n" +  @billing_address.country+ "\n"

      pdf.pad_top (40) {pdf.text text_block, align: :left, size: 12 }
      pdf.pad_top (40) {pdf.text "Vienna, #{@payment.created_at.strftime("%Y-%m-%d")}", align: :right, size: 12 }
      pdf.pad_top (20) {pdf.text "Dear #{current_user.member.title} #{current_user.member.firstname} #{current_user.member.lastname} #{current_user.member.grade},\n this is a confirmation of your payment for the EFDMA membership fee for the next year starting today (#{@payment.created_at.strftime("%Y-%m-%d")}).", align: :left, size: 12}
      pdf.pad_top (20) {pdf.text "We successfully received your payment of € 140,-.", align: :left, size: 12, style: :bold}
      pdf.pad_top (20) {pdf.text "Thank you for being a part of EFDMA.", align: :left, size: 12}
      pdf.pad_top (40) {pdf.text "Yours sincerely,\n\n Lars Werner\nTreasurer EFDMA", align: :left, size: 12}

      pdf.bounding_box([0,50], width: 150, height: 50) do
        
        pdf.text "EFDMA\nLerchenfelder Straße 66-68/1/52\nA-1080 Vienna", size: 10
      end
      pdf.bounding_box([190,50], width: 150, height: 50) do
        
        pdf.text "www.fdm-europe.com\noffice@fdm-europe.com\nZVR 898629488", size: 10, align: :center
      end
      pdf.bounding_box([370,50], width: 150, height: 50) do
        
        pdf.text "IBAN: AT401200050030001405\nBIC:BKAUATWW\nBank Austria - Creditanstalt", size: 10, align: :right
      end

app/controllers/users/payments_controller.rb
class Users::PaymentsController < Devise::SessionsController
	def add_payment
	end

	def quit_payment
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :paymill_customer_id %><br>
    <%= f.text_field :paymill_customer_id %>
  </div>
  <div class="field">
    <%= f.label :next_payment %><br>
    <%= f.date_select :next_payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/change_payment.html.erb
<p><%= @payment_old.to_json %></p>
<p><%= @subscription.to_json %></p>

app/views/payments/edit.html.erb
<h1>Editing Payment Channel</h1>



<form id="payments" method="post" action="<%= change_path %>">
  <div id="payment-form"></div>
  <input type="submit" value="Update payment method" >  
</form>



<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

<script>
  braintree.setup(
    "<%= @token %>",
    "dropin", {
      container: "payment-form"
    });
</script>


<%= link_to 'back', payments_path %> 

app/views/payments/index.html.erb
<% unless @payment.payment_customer_id.nil? %>
<div class="row">

	<div class="col-md-5">
		<h1>Your Payment Details</h1>

		<% payment = @payment_info %>
			<% if @payment_method.class == Braintree::PayPalAccount %>

			<div class="well">
				
				<a class="pull-right" href="<%= edit_payment_path(current_user.payments.last.id) %>" data-turbolinks="false">Change type of payment</a>
				<small>Your current payment channel</small>

				<p>Type: <%= image_tag @payment_method.image_url %> | Email: <%= @payment_method.email %>  </p>
			</div>

			<% else %>

			<div class="well">
				
				<a class="pull-right" href="<%= edit_payment_path(current_user.payments.last.id) %>" data-turbolinks="false">Change</a>
				<small>Your current payment channel</small>

				<h3><%= @payment_method.bin %>****<%= @payment_method.last_4 %></h3>
				<p>Type: <%= image_tag @payment_method.image_url %> | Expires on: <%= @payment_method.expiration_month %>/<%= @payment_method.expiration_year %>  </p>
			</div> 

			<% end %>


		
		
	</div>
	
	
</div>
<% else %>

<div class="row">

	<div class="col-md-5">
		<h1>Your Payment Details</h1>

		
			<div class="well">
				
				<a class="pull-right" href="<%= edit_payment_path(current_user.payments.last.id) %>" data-turbolinks="false">Change type of payment</a>
				<small>Your current payment channel</small>

				<p>Sofortüberweisung </p>
			</div>

			


		
		
	</div>
	
	
</div>


<% end %>




<% if @payment.payment_customer_id.nil? %>

<div class="row">
	<div class="col-md-12">
		<div class="alert alert-info" role="alert">
			<p class="bg-default">Your next membership payment is due on: <strong><%= @payment.next_payment %></strong> and will be <strong>&euro; 100,-</strong>.</p>
		</div>
			
		
	</div>
	
</div>


<div class="row">
	<div class="col-md-12">
		<h2>Your Payments</h2>
		
		<div class="table-responsive">
			<table class="table table-striped">

				<thead>
					<tr>
						<th>Date</th>
						
						
						
						<th>Amount</th>
						<th>Download</th>
					</tr>
				</thead>
				<tbody>
						<% @payments.each do |payment| %>
						<tr>
							<td>
								<%= payment.created_at.strftime("%Y-%m-%d") %>
							</td>
							
							<td>
								&euro; 140,-
							</td>

							<td><%= button_to "show payment confirmation", show_invoice_sofort_path, class: "btn btn-default", method: :post, params: {id: payment.id} %></td>
						</tr>
						<% end %>
					
				</tbody>
			</table>
		</div>
		
	</div>
	
	
</div>


<% else %>

<div class="row">
	<div class="col-md-12">
		<div class="alert alert-info" role="alert">
			<p class="bg-default">Your next automatic membership payment is due on: <strong><%= (@transactions.first.created_at + 1.year).strftime("%Y-%m-%d") %></strong> and will be <strong>&euro; 140,-</strong>.</p>
		</div>
			
		
	</div>
	
</div>


<div class="row">
	<div class="col-md-12">
		<h2>Your Payments</h2>
		
		<div class="table-responsive">
			<table class="table table-striped">

				<thead>
					<tr>
						<th>Date</th>
						<th>Card number</th>
						
						
						<th>Amount</th>
						<th>Download</th>
					</tr>
				</thead>
				<tbody>
					<% for transaction in @transactions %>

						<tr>
							<td>
								<%= transaction.created_at.strftime("%Y-%m-%d") %>
							</td>
							
							<td>
								<% if transaction.credit_card_details.bin %>
								<%= transaction.credit_card_details.bin %>****<%= transaction.credit_card_details.last_4 %>
								<% end %>
							</td>

								
							<% if transaction.status == "settled" %>
							<td>&euro; <%= transaction.amount %></td>
							<td><%= button_to "show payment confirmation", show_invoice_path, params: {transaction_id: transaction.id}, class: "btn btn-default", method: :post %></td>

							<% else %>

							<td>&euro; <%= transaction.status %></td>
							<td></td>

							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		
	</div>
	
	
</div>

<% end %>

app/views/payments/new.html.erb
<div class="row">
    <% if current_user.member.member_type == 0 %>
    <div class="col-md-12">
        <h1>Become a full member</h1>
        <p><%= current_user.member.full_name %>, becoming a full member with the EFDMA covers these advantages for you:</p>
        <ul>
            <li><strong>Members are listed in the register of FDM Practitioners</strong></li>
            <ul>
                <li>with contact data and picture, if they can provide proof for having obtained the FDM Basic Certificate (FDM BC)</li>
                <li>as FDM Practitioners in training without contact data, if they have not yet obtained the FDM BC</li>
            </ul>
            <li><strong>Possibility to participate in local FDM Workgroups</strong></li>
            <li><strong>Possibility to benefit from the network of FDM Practitioners and exchange with them</strong></li>
            <li><strong>Newsletter with information about FDM Workgroups, training and continuing education seminars as well as current research and development regarding the FDM and Typaldos method</strong></li>
            <li><strong>Password-protected member area on our website offering:</strong></li>
            <ul>
                <li>Possibility to update your profile</li>
                <li>Templates for various forms (e.g. patient information folder)</li>
                <li>Information about studies regarding the FDM and associated topics</li>
                <li>Information about discounts</li>
                <li>Teaching contents (e.g. webinars, congress contributions, etc.)</li>
                <li>News for members</li>
            </ul>
        </ul>
        
    </div>
    <% end %>
</div>
<hr>
<div class="row">

    <div class="col-md-12">

        <h2>Membership fee and payment</h2>      
        <p>The annual membership fee of the EFDMA is <strong>&euro; 140,-</strong>. You can pay our fee using the following payment gateways. If you have questions or cannot pay using one of the provided gateways please don't hesitate to contact us via email: <a href="mailto: office@fdm-europe.com">office@fdm-europe.com</a>.</p>

        <p>
            Currently you can pay your annual membership fee with the following payment gateways.
        </p>
        <ul>
            <li>Maestro (Debitcard)</li>
            <li>Maestro UK (Debitcard)</li>
            <li>Master Card</li>
            <li>Visa</li>
            <li>Discover</li>
            <li>PayPal</li>
            <li>Sofort &Uuml;berweisung</li>
            
            
        </ul>
        <p class="well"><strong>You can use the form below to either fill in your Maestro or credit card information or click the PayPal-Button to pay using PayPal.<br> <i>On some Maestro cards you only see "valid through" and the year. Please type in 12 for month and your year as the expiration date in the form below.</i></strong></p>
    </div>
</div>
<hr>
<p>
<%= link_to send_sofort_payment_path  do %>
    <%= image_tag("sofortueberweisung.jpg", width: 101, alt: "Sofortüberweisung") %>
<% end %>
<- New
</p>






<form id="payments" method="post" action="/payments">
<div class="col-md-12 hide-me">
                  <p class="bg-danger"> You need to activate Javascript in order to see the payment form. <a href="http://www.enable-javascript.com" target="_blank">Please click here to find out how.</a></p>
                  
</div>
  <div id="payment-form"></div>
  <input type="submit" value="Submit">
</form>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

<script typy="text/javascript">
  braintree.setup(
    // Replace this with a client token from your server
    "<%= @token %>",
    "dropin", {
      container: "payment-form"
    });

    $(document).ready(function(){
        $(".hide-me").hide();
    });
</script>

app/views/payments/send_sofort_payment.html.erb
<%= @response %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @payment.user_id %>
</p>

<p>
  <strong>Paymill customer:</strong>
  <%= @payment.paymill_customer_id %>
</p>

<p>
  <strong>Next payment:</strong>
  <%= @payment.next_payment %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/payments/sofort_payment.html.erb
<%= @response %>