config/routes.rb
Rails.application.routes.draw do
  
  resources :scholars
  resources :quit_accounts
  get 'coupon/check_coupon'

  resources :member_files
  resources :payments
  
  get 'admin/stats'
  get "/admin/new_payment_for_member/:user_id" => "admin#new_payment_for_member", as: "new_payment_for_member"
  post "/admin/create_payment_for_member" => "admin#create_payment_for_member"

  get "admin/look_up" => "admin#look_up"
  get "admin/edit_user/:user_id" => "admin#edit_user", as: "admin_edit_user"
  
  patch "admin/change_user/:user_id" => "admin#change_user", as: "admin_change_user"

  post "change_payment" => "payments#change_payment", as: "change"
  post "list_searched_members" => "admin#list_searched_members", as: "list_searched_members"

  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", payments: "users/payments", passwords: "users/passwords" }
  get "/profile" => "members#edit"
  get "/dashboard/:member_id" => "members#dashboard", as: "dashboard"
  resources :members 

  resources :addresses
  resources :users

  resources :certificates
  post "certificate/save_certificate" => "certificates#save_certificate"
  
  get "members/:id/add_certificate" => "members#add_certificate"
  post "members/:id/save_certificate" => "members#save_certificate"
  get "members/show_members" => "members#show_members"
  get "member_search" => "addresses#search"
  get "lastnames" => "members#lastnames", as: "lastnames"
  get "search_by_name" => "members#search_by_name", as: "search_by_name"

  get "/contact" => "members#contact", as: "contact"
  post "/send_contact" => "members#send_contact", as: "send_contact"
  
  post "/show_invoice" => "payments#show_invoice", as: "show_invoice"
  post "/show_invoice_sofort" => "payments#show_invoice_sofort", as: "show_invoice_sofort"
  get "/admin/show_invoice/:user_id" =>"admin#show_invoice", as: "admin_show_invoice"
  get "/edit_overview" => "courses#edit_overview", as: "edit_overview"
  
  post "resend_member_email/:user_id" => "admin#resend_member_email"

  get "/admin/:user_id/addresses/new" => "admin#new_address", as: "admin_new_address"
  post "admin/:user_id/addresses" => "admin#create_address", as: "admin_create_address"
  delete "admin/addresses/:id" => "admin#destroy_address", as: "admin_destroy_address"
  get "admin/addresses/:id" => "admin#edit_address", as: "admin_edit_address"
  patch "admin/addresses/:id" => "admin#update_address", as: "admin_update_address"
  get "admin/has_paid" => "admin#has_paid"
  post "admin/send_payment_reminder" => "admin#send_payment_reminder"
  get "admin/new_user" => "admin#new_user"
  post "admin/create_user" => "admin#create_user", as: "admin_create_user"
  post "admin/user/:id" => "admin#delete_user", as: "admin_delete_user"
  get "admin/organizer/new" => "admin#new_organizer"
  get "admin/organizer/edit/:id" => "admin#edit_organizer", as: "admin_edit_organizer"
  post "admin/organizer" => "admin#create_organizer", as: "admin_create_organizer"
  patch "admin/organizer/:id" => "admin#update_organizer", as: "admin_update_organizer"
  get "admin/organizers" => "admin#index_organizers", as: "admin_organizers"
  post "admin/organizers/delete/:id" => "admin#delete_organizer", as: "admin_delete_organizer"
  get "admin/who_became_member" => "admin#who_became_member", as: "who_became_member"
  get "sofort/receive" => "payments#sofort_payment", as: "sofort_payment"

  post "sofort/success" => "payments#sofort_success", as: "sofort_success"
  get "sofort/sent_sofort" => "payments#send_sofort_payment", as: "send_sofort_payment"

  get "coupon/check" => "coupon#check", defaults: { format: "json"}
  get "coupon/used_now" => "coupon#used_now", defaults: { format: "json"} 
  

  get "save_congress_member" => "members#save_congress_member"
  get "admin/quit_member" => "quit_accounts#index", as: "admin_quit_members"

  post "admin/webhooks" => "admin#braintree_webhooks"

  get "scholars/external/:link" => "scholars#external_link"
  post "scholars/list_searched_scholars" => "scholars#list_searched_scholars"

   root 'members#dashboard'

end

app/models/member_file.rb
class MemberFile < ActiveRecord::Base
	mount_uploader :document, DocumentUploader
	has_one :document


end

app/controllers/member_files_controller.rb
class MemberFilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_member_file, only: [:show, :edit, :update, :destroy]

  # GET /member_files
  # GET /member_files.json
  def index
    @member_files = MemberFile.all
    if Scholar.all.where(public: true).count > 0
      @scholars = Scholar.where(public: true)
    end
  end

  # GET /member_files/1
  # GET /member_files/1.json
  def show
  end

  # GET /member_files/new
  def new
    unless current_user.has_role?("admin")
      redirect_to member_files_path, notice: "You are not allowed to upload files"
    end
    @member_file = MemberFile.new
  end

  # GET /member_files/1/edit
  def edit
    unless current_user.has_role?("admin")
      redirect_to member_files_path, notice: "You are not allowed to edit files"
    end
  end

  # POST /member_files
  # POST /member_files.json
  def create
    @member_file = MemberFile.new(member_file_params)

    respond_to do |format|
      if @member_file.save
        format.html { redirect_to member_files_path, notice: 'File was successfully uploaded.' }
        format.json { render :show, status: :created, location: @member_file }
      else
        format.html { render :new }
        format.json { render json: @member_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_files/1
  # PATCH/PUT /member_files/1.json
  def update
    respond_to do |format|
      if @member_file.update(member_file_params)
        format.html { redirect_to @member_file, notice: 'File was successfully updated.' }
        format.json { render :show, status: :ok, location: @member_file }
      else
        format.html { render :edit }
        format.json { render json: @member_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_files/1
  # DELETE /member_files/1.json
  def destroy
    unless current_user.has_role?("admin")
      redirect_to member_files_path, notice: "You are not allowed to delete files"
    end
    @member_file.destroy
    respond_to do |format|
      format.html { redirect_to member_files_url, notice: 'File was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_file
      @member_file = MemberFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_file_params
      params.require(:member_file).permit(:name, :category, :document)
    end
end

app/helpers/member_files_helper.rb
module MemberFilesHelper
end

app/views/member_files/_form.html.erb
<%= form_for(@member_file) do |f| %>
  <% if @member_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_file.errors.count, "error") %> prohibited this member_file from being saved:</h2>

      <ul>
      <% @member_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.select(:category,MemberFile.all.map(&:category).uniq, class: "form-control") %> <button id="model-opener"><i class="fa fa-plus"></i> add category</button>
  </div>


  <div class="form-group">
      

      
      <%= f.file_field :document, class: "form-control", required: true %> 
      <p>All file formats are allowed</p>
      
    </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>


<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add file category</h4>
      </div>
      <div class="modal-body">
        <p><label>name <input type="text" placeholder="add category name" id="new_category_name"></label></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="add_category" type="button" class="btn btn-primary">Add name</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
  $(document).ready(function(){
    $("#model-opener").on("click", function(e){
      e.preventDefault();

      $(".modal").modal("toggle");

    });
    $("#add_category").on("click", function(){

        $val = $("#new_category_name").val();
        console.log($val);
        $("#member_file_category").prepend($("<option/>", {value: $val, text: $val}));
        $(".modal").modal("toggle");
    });
  });
</script>

app/views/member_files/edit.html.erb
<h1>Editing File</h1>

<%= render 'form' %>

<%= link_to 'Back', member_files_path %>

app/views/member_files/index.html.erb
<h1>Listing Member Files</h1>
<p>These documents are <strong>ONLY</strong> available for <strong>EFDMA MEMBERS</strong>. The authorization of the use of these documents is only valid during the membership in the EFDMA. A forwarding to other persons is <strong>NOT</strong> allowed.</p>
<% if current_user.has_role?("admin") %>
  <%= link_to(new_member_file_path, class:"btn btn-success") do  %>
    <span style="color: white;">Upload new file</span>
  <% end %>
  <hr>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>File</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @member_files.each do |member_file| %>
      <tr>
        <td><%= member_file.name %></td>
        <td><%= member_file.category %></td>
        <td><%= link_to "Download file", member_file.document.url, class: "btn btn-success", target: '_new' %></td>
        <% if current_user.has_role?("admin") %>
        <td><%= link_to(edit_member_file_path(member_file), class: "btn btn-default") do  %>
            <i class="fa fa-pencil fa-fw"></i>
          <% end %> 

          <%= link_to member_file, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do  %>
            <i style="color: white;" class="fa fa-trash"></i>
          <% end %></td>
          <% end %>
        


        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @scholars %>
  <h2>Scientific Documents</h2>
  <table class="table">
  <thead>
    <tr>
      <th width="50%">Title</th>
      <th>Author</th>
      
      
      
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scholars.each do |scholar| %>
      <tr>
        <td><%= scholar.title %></td>
        <td><%= scholar.author %></td>
        
        
        
        <td><%= link_to 'Download file', "#{root_url}scholars/external/#{scholar.link}", class: "btn btn-success" %>
        <% if current_user.has_role?("admin") %>
        <%= link_to edit_scholar_path(scholar), class: "btn btn-default" do  %>
          <i class="fa fa-pencil fa-fw"></i>
          <% end %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/member_files/new.html.erb
<h1>New Member File</h1>

<%= render 'form' %>

<%= link_to 'Back', member_files_path %>

app/views/member_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member_file.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @member_file.category %>
</p>

<%= link_to 'Edit', edit_member_file_path(@member_file) %> |
<%= link_to 'Back', member_files_path %>