config/routes.rb
Rails.application.routes.draw do
  
  resources :scholars
  resources :quit_accounts
  get 'coupon/check_coupon'

  resources :member_files
  resources :payments
  
  get 'admin/stats'
  get "/admin/new_payment_for_member/:user_id" => "admin#new_payment_for_member", as: "new_payment_for_member"
  post "/admin/create_payment_for_member" => "admin#create_payment_for_member"

  get "admin/look_up" => "admin#look_up"
  get "admin/edit_user/:user_id" => "admin#edit_user", as: "admin_edit_user"
  
  patch "admin/change_user/:user_id" => "admin#change_user", as: "admin_change_user"

  post "change_payment" => "payments#change_payment", as: "change"
  post "list_searched_members" => "admin#list_searched_members", as: "list_searched_members"

  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", payments: "users/payments", passwords: "users/passwords" }
  get "/profile" => "members#edit"
  get "/dashboard/:member_id" => "members#dashboard", as: "dashboard"
  resources :members 

  resources :addresses
  resources :users

  resources :certificates
  post "certificate/save_certificate" => "certificates#save_certificate"
  
  get "members/:id/add_certificate" => "members#add_certificate"
  post "members/:id/save_certificate" => "members#save_certificate"
  get "members/show_members" => "members#show_members"
  get "member_search" => "addresses#search"
  get "lastnames" => "members#lastnames", as: "lastnames"
  get "search_by_name" => "members#search_by_name", as: "search_by_name"

  get "/contact" => "members#contact", as: "contact"
  post "/send_contact" => "members#send_contact", as: "send_contact"
  
  post "/show_invoice" => "payments#show_invoice", as: "show_invoice"
  post "/show_invoice_sofort" => "payments#show_invoice_sofort", as: "show_invoice_sofort"
  get "/admin/show_invoice/:user_id" =>"admin#show_invoice", as: "admin_show_invoice"
  get "/edit_overview" => "courses#edit_overview", as: "edit_overview"
  
  post "resend_member_email/:user_id" => "admin#resend_member_email"

  get "/admin/:user_id/addresses/new" => "admin#new_address", as: "admin_new_address"
  post "admin/:user_id/addresses" => "admin#create_address", as: "admin_create_address"
  delete "admin/addresses/:id" => "admin#destroy_address", as: "admin_destroy_address"
  get "admin/addresses/:id" => "admin#edit_address", as: "admin_edit_address"
  patch "admin/addresses/:id" => "admin#update_address", as: "admin_update_address"
  get "admin/has_paid" => "admin#has_paid"
  post "admin/send_payment_reminder" => "admin#send_payment_reminder"
  get "admin/new_user" => "admin#new_user"
  post "admin/create_user" => "admin#create_user", as: "admin_create_user"
  post "admin/user/:id" => "admin#delete_user", as: "admin_delete_user"
  get "admin/organizer/new" => "admin#new_organizer"
  get "admin/organizer/edit/:id" => "admin#edit_organizer", as: "admin_edit_organizer"
  post "admin/organizer" => "admin#create_organizer", as: "admin_create_organizer"
  patch "admin/organizer/:id" => "admin#update_organizer", as: "admin_update_organizer"
  get "admin/organizers" => "admin#index_organizers", as: "admin_organizers"
  post "admin/organizers/delete/:id" => "admin#delete_organizer", as: "admin_delete_organizer"
  get "admin/who_became_member" => "admin#who_became_member", as: "who_became_member"
  get "sofort/receive" => "payments#sofort_payment", as: "sofort_payment"

  post "sofort/success" => "payments#sofort_success", as: "sofort_success"
  get "sofort/sent_sofort" => "payments#send_sofort_payment", as: "send_sofort_payment"

  get "coupon/check" => "coupon#check", defaults: { format: "json"}
  get "coupon/used_now" => "coupon#used_now", defaults: { format: "json"} 
  

  get "save_congress_member" => "members#save_congress_member"
  get "admin/quit_member" => "quit_accounts#index", as: "admin_quit_members"

  post "admin/webhooks" => "admin#braintree_webhooks"

  get "scholars/external/:link" => "scholars#external_link"
  post "scholars/list_searched_scholars" => "scholars#list_searched_scholars"

   root 'members#dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Efdma</title>
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

    <body>
      <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= root_url() %>"><%= image_tag("transparent_white.png", alt: "EFDMA", class: "img-responsive")  %></a>
          </div>
          <!-- Top Menu Items -->
          <ul class="nav navbar-right top-nav">
            <li><a href="<%= edit_member_path(current_user.member) %>">logged in as <%= current_user.member.full_name %></a></li>
            <li class="dropdown">
              
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cog"></i> Settings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to payments_path, data: { no_turbolink: true } do %>
                    <i class="fa fa-fw fa-money"></i> Payments
                  <% end %>
                </li>
                <li>
                  <a href="<%= edit_user_registration_path %>"><i class="fa fa-fw fa-gear"></i> Login Info</a>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do  %>
                    <i class="fa fa-fw fa-power-off"></i> Log Out
                  <% end %>
                  
                </li>
              </ul>
            </li>
          </ul>
          <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
              <li <% if params[:controller] == "members" && params[:action] == "dashboard" %>class="active"<% end %>>
                <%= link_to dashboard_path(current_user.member) do %>
                  <i class="fa fa-fw fa-dashboard"></i> Dashboard
                <% end %>
                </a>
              </li>
              <li <% if params[:controller] == "members" && params[:action] == "edit" %>class="active"<% end %>>
                <%=  link_to edit_member_path(current_user.member) do %>
                  <i class="fa fa-fw fa-user"></i> Profile
                <% end %>
                
              </li>
              
                <li <% if params[:controller] == "courses" %>class="active"<% end %>>
                  <%= link_to courses_path do %>
                    <i class="fa fa-fw fa-book"></i> Courses
                  <% end %>
                  <% if current_user.has_role? :admin or current_user.has_role? :instructor or current_user.has_role? :organizer %>
                    <ul class="collapse in">
                      <li><%= link_to "Edit your courses", edit_overview_path %></li>
                      <li><%= link_to "Create new course", new_course_path %></li>
                    </ul>
                  <% end %>
                  
                </li>
              
              <li <% if params[:controller] == "certificates"  %>class="active"<% end %>>
                <%= link_to certificates_path do %>
                  <i class="fa fa-fw fa-certificate"></i> Certificate
                <% end %>
                  <% if current_user.has_role? :admin or current_user.has_role? :instructor  %>
                    <ul class="collapse in">
                      <li>
                        <%= link_to new_certificate_path do %>
                          Create new certificates
                        <% end %>
                      </li>
                    </ul>
                  <% end %>
              </li>
              <li>
                <%= link_to(member_files_path) do %>
                  <i class="fa fa-fw fa-download"></i> Member files
                <% end %>
              </li>
              <li <% if params[:controller] == "members" && params[:action] == "contact" %>class="active"<% end %>>
                <%= link_to contact_path do %>
                  <i class="fa fa-fw fa-envelope-o"></i> Contact
                <% end %>
                
              </li>
              <% if current_user.has_role? :admin %>
              <li <% if params[:controller] == "admin" %>class="active"<% end %>>
              <%= link_to admin_stats_path do %>
                  <i class="fa fa-fw fa-lock"></i> Admin statistics
                <% end %>
                  <ul class="collapse in">
                    <li><%= link_to "Look up user", admin_look_up_path %></li>
                    <li><%= link_to "New Member", admin_new_user_path %></li>
                    <li><%= link_to "Member Payments", admin_has_paid_path %></li>
                    <li><%= link_to "Organizers", admin_organizers_path %></li>
                    <li><%= link_to "New organizer", admin_organizer_new_path %></li>
                    <li><%= link_to "Quit members", admin_quit_members_path %></li>
                  </ul>
                
              </li>
              <% end %>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </nav>
        <div id="page-wrapper">
          <div class="container-fluid">
            <div class="alerts">
              
            
            <div class="row">
              <% if flash[:alert] %>
              <div class="col-md-12">
                <p class="bg-danger"><%= flash[:alert] %></p>  
              </div>
              
              <% end %>
              <% if flash[:notice] %>
              <div class="col-md-12">
                <p class="bg-primary"><%= flash[:notice] %></p>  
              </div>
              
              <% end %>

              <% if current_user.member.member_type == 0 && current_user.member.trial_ends > Time.now %>
                <div class="col-md-12">
                  <p class="bg-success"> Your trail membership ends in <%= ((current_user.member.trial_ends - Time.now)/60/60/24).round(0) %> days. <%= link_to "See your advantages in becoming a full member today.", payments_path, data: { no_turbolink: true } %> <br> From October 2nd, 2017 the membership fee amounts  € 140, -.-</p>
                </div>
                
              

              <% elsif current_user.member.member_type > 0  && current_user.payments.last.nil? %>
                <div class="col-md-12">
                  <p class="bg-danger"> Your membership payment is due. Please add your payment method here: <%= link_to "Click here to pay your membership", payments_path, data: { no_turbolink: true } %> .</p>
                </div>
                
              <% elsif current_user.member.member_type > 0 && current_user.payments.last.next_payment < Date.today + 3.weeks && current_user.payments.last.payment_customer_id.nil? %>

                <div class="col-md-12">
                  <p class="bg-danger"> Your membership payment is due. Please add your payment method here: <%= link_to "Click here to pay your membership", new_payment_path, data: { no_turbolink: true } %> .</p>  
                </div>

                

              <% end %>




              
              
            </div>
            </div>
            
            <%= yield %>
            
          </div>
        </div>
      </div>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76771509-1', 'auto');
  ga('send', 'pageview');

</script>
    </body>
  </html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Efdma</title>
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="empty">
  <%= yield %>
  </body>
  </html>